baseURL = "https://c13n.io"
languageCode = "en-us"
title = "c13n"
theme = "gokarna"

[menu]
    [[menu.main]]
        identifier = "home"
        url = "/"
        name = "Home"
        weight = 1
    [[menu.main]]
        identifier = "about"
        url = "/about/"
        name = "About"
        weight = 2
    [[menu.main]]
        identifier = "contact"
        url = "/contact/"
        name = "Contact"
        weight = 4
[params]
    avatarURL = "c13n-avatar.png"
    avatarSize = "size-xl"
    description = "Gain Lightning powers, today"
    footer = "c13n.io"
    socialIcons = [
      {name = "twitter", url = "https://twitter.com/c13n_io"},
      {name = "github", url = "https://github.com/c13n-io"},
    ]