baseURL = "https://c13n.io"
languageCode = "en-us"
title = "c13n"
theme = "gokarna"

[menu]
    [[menu.main]]
        identifier = "home"
        url = "/"
        name = "Home"
        weight = 1
    [[menu.main]]
        identifier = "about"
        url = "/about/"
        name = "About"
        weight = 2
    [[menu.main]]
        identifier = "contact"
        url = "/contact/"
        name = "Contact"
        weight = 4
[params]
    avatarURL = "https://c13n.io/c13n-avatar.png"
    avatarSize = "size-xl"
    description = "Gain Lightning powers, today"
    footer = "c13n"
    socialIcons = [
      #{name = "twitter", url = "https://twitter.com/c13n_io"},
      {name = "github", url = "https://github.com/c13n-io"},
      {name = "slack", url = "https://join.slack.com/t/c13n/shared_invite/zt-wkk5cu44-Zf4iXr9mxNHzW_ZRBZsDQA"},
    ]
    contactpoints = [
      #{name = "twitter", title = "Twitter", url = "https://twitter.com/c13n_io"},
      {name = "github", title = "GitHub", url = "https://github.com/c13n-io"},
      {name = "slack", title = "Slack", url = "https://join.slack.com/t/c13n/shared_invite/zt-wkk5cu44-Zf4iXr9mxNHzW_ZRBZsDQA"},
      {name = "mail", title = "contact@c13n.io", url = "mailto:contact@c13n.io"},
    ]